In [3]:
import numpy as np


In [5]:
a = np.array([1,3,9,0,'hello'])
print(a)

['1' '3' '9' '0' '2']


In [13]:
np_arr = np.array([3,3,3,3.3,'hello',False])
print(np_arr)
# print(bool(np_arr[-1]))

# a = False
# print(bool(a))

['3' '3' '3' '3.3' 'hello' 'False']


In [10]:
a = '0'
print(bool(a))

True


In [41]:
a = np.zeros((3,2,4), dtype = int)
print(a)
# print(type(a[0][0][0]))
# dtype int make datatype int


[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]


In [27]:
a = np.empty((2,3))
print(a)

[[5.64132349e-315 0.00000000e+000 6.62228001e-310]
 [6.62228001e-310 6.62228001e-310 6.62228001e-310]]


In [29]:
a = np.full(3,5)
print(a)

[5 5 5]


In [40]:
a = np.arange(3,12,4)
a = np.linspace(3,8,5)
print(a)

[3.   4.25 5.5  6.75 8.  ]


In [50]:
a = np.ones((3,2), dtype = int)
print(a.shape)
print(a.size)


(3, 2)
6


In [61]:
a = np.random.randint(1,8,4)
print(a)

[6 3 5 7]


In [63]:
a = np.random.choice([2,3,4,5,6,7],4)
print(a)

[5 2 4 3]


In [79]:
a = np.ones((2,3,4),dtype= int)
b = np.random.randint((2,10,5),dtype = int)
print(b)

b = a .reshape((3,2))

# print(a*b)
# print(a/b)
# print(a+b)
# print(2*a)


[0 8 3]


In [103]:
# print(a)

# b = a.transpose()
# print(b)

a = np.random.randint(2,10,5)

c = np.random.randint(2,10,5)
print(np.concatenate((a,c),))



[8 6 2 9 5 3 6 5 9 5]


In [113]:

a = np.random.randint(2,10,5)

b = np.random.randint(6,20,5)
print(a)
print(b)

c = np.where((b>5)&(b%3),b,a)
print(c)


[2 5 2 4 4]
[ 8 18 17  7  8]
[2 5 2 7 4]


In [124]:
gill = np.array([200,300,100,55,30])
minim = gill.min()
print("Minimum :" , minim)

max = gill.max()
print("Maximum :" , max)

differ = np.unique(gill)
print("Unique :" ,differ)

mat = np.matmul(gill,gill)
print(mat)


Minimum : 30
Maximum : 300
Unique : [ 30  55 100 200 300]
143925


In [ ]:
score = []
days = ['mon','tue','wed','thu','fri']

for i in range(7):
  x = input(f'give the input for the {days[i]}: ')

In [126]:
scores = input().split()
print(scores)

scores = [int(x) for x in scores]
print(scores)

20 30 40 50 
['20', '30', '40', '50']
[20, 30, 40, 50]
