<a href="https://colab.research.google.com/github/himanshu180105/Data_Science/blob/main/Pandas_lect05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
products = []
name = ['sugar', 'salt', 'apple', 'banana', 'ladyfinger']

for i in range(5):
 x = input(f'give the input for the {name[i]}:')





give the input for the sugar:42
give the input for the salt:18
give the input for the apple:100
give the input for the banana:60
give the input for the ladyfinger:30


In [17]:
# ques on numpy
# 2 ques of numpy

import numpy as np

mat = np.random.randint(1,90,(5,5))
print(mat)

row_mean = np.mean(mat , axis = 1)
print(row_mean)
column_mean = np.mean(mat, axis = 0)
print(column_mean)

Replace_even = np.where(mat%2==0, -1, mat)
print(Replace_even)

sorted_row = np.sort(mat, axis=1)
sorted_col = np.sort(mat , axis = 0)
print(sorted_row)
print(sorted_col)

sum_row = np.sum(mat , axis = 1)
sum_col = np.sum(mat , axis = 0)

# count_col = np.sum(np.where(modified_mat < 0,1 ,0),axis = 0)
# print(count_col)



[[64  6 60 53 18]
 [76 54 30  7 15]
 [65  9 64 81 39]
 [23 61 11 84 48]
 [61 57 86 71 57]]
[40.2 36.4 51.6 45.4 66.4]
[57.8 37.4 50.2 59.2 35.4]
[[-1 -1 -1 53 -1]
 [-1 -1 -1  7 15]
 [65  9 -1 81 39]
 [23 61 11 -1 -1]
 [61 57 -1 71 57]]
[[ 6 18 53 60 64]
 [ 7 15 30 54 76]
 [ 9 39 64 65 81]
 [11 23 48 61 84]
 [57 57 61 71 86]]
[[23  6 11  7 15]
 [61  9 30 53 18]
 [64 54 60 71 39]
 [65 57 64 81 48]
 [76 61 86 84 57]]


In [18]:
import numpy as np

stock = np.random.randint(20,80,(5,5))
demand = np.random.randint(20,80,(5,5))

remaining_stock = np.subtract(stock,demand)

Replace_negative = np.where(remaining_stock<0 ,0, remaining_stock)

# total shortage
total_shortage = np.sum (np.where(remaining_stock < 0,remaining_stock* -1,0),axis = 0)


# products with zero stock
num_zeros = np.sum(np.where(remaining_stock < 0,1,0), axis=0)
print(num_zeros)


sorted = np.sort(Replace_negative, axis = 1)






[4 2 3 3 4]


In [27]:
# starting of pandas
import pandas as pd
file_ = pd.read_csv("./student_data(DS).csv", sep =',')
print(file_.head(8))


   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
5                      0            